version: "2"

run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - revive

linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: blank-imports
      - name: early-return

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
